trigger:
- master   

pool:
  name: Default  

variables:
  PYTHON_VERSION: '3.10'

stages:

# ========================
# 1) CI : Build & Package
# ========================
- stage: Build
  displayName: "Build and Package"
  jobs:
  - job: Build
    steps:
    - task: UsePythonVersion@0
      displayName: 'Use Python $(PYTHON_VERSION)'
      inputs:
        versionSpec: '$(PYTHON_VERSION)'
        addToPath: true

    - script: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt --target=".python_packages/lib/site-packages"
      displayName: 'Install dependencies → .python_packages/'

    - task: CopyFiles@2
      displayName: 'Stage files for package'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: |
          host.json
          local.settings.json
          requirements.txt
          shared.py
          **/*.py
          .python_packages/**/*
          !.git/**/*
          !.vscode/**/*
          !**/__pycache__/**/*
          !**/*.pyc
          !**/.venv/**/*
        TargetFolder: '$(Build.ArtifactStagingDirectory)/package'

    - task: ArchiveFiles@2
      displayName: 'Zip package'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/package'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)'
      artifact: drop
# ========================
# 2) CD : Deploy to Azure (Publish Profile)
# ========================
- stage: Deploy
  displayName: "Deploy to Azure Function"
  dependsOn: Build
  jobs:
  - deployment: DeployToAzure
    displayName: "Deploy Function App"
    environment: 'dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          # (Optional) sanity check: list downloaded files
          - powershell: |
              Write-Host "Listing $(Pipeline.Workspace)\drop"
              Get-ChildItem -Recurse "$(Pipeline.Workspace)/drop" | Select-Object FullName, Length
            displayName: 'List downloaded artifact'

          # Zip Deploy using publish profile (NO service connection)
          - task: AzureWebApp@1
            displayName: 'Zip Deploy via Publish Profile'
            inputs:
              appType: 'functionApp'                 # use 'functionApp' if your Function App is Window
              appName: 'amira-functionapp'
              package: '$(Pipeline.Workspace)/drop/functionapp.zip'
              publishProfile: '$(AZURE_FUNCTIONAPP_PUBLISH_PROFILE)'


