resources:
  pipelines:
  - pipeline: ci
    source: "azure-pipelines"      # nom du pipeline CI (pas le fichier, pas le projet)
    project: "amira2200.pfe2025"   # ton projet DevOps
    branch: master                 # ou main selon ta branche
    trigger: true

pool:
  name: Default

variables:
  functionAppName: 'amira-functionapp'
  artifactName: 'drop'
  packagePath: '$(Pipeline.Workspace)/ci/$(artifactName)/functionapp.zip'

stages:
- stage: Deploy
  displayName: 'Deploy to Azure Functions (Windows)'
  jobs:
  - job: DeployJob
    steps:
    - download: ci
      artifact: $(artifactName)

    - task: AzureFunctionApp@2
      displayName: 'Deploy $(packagePath) to $(functionAppName)'
      inputs:
        connectedServiceNameARM: 'Azure subscription 1 (79d70fcd-2018-4a86-bbf8-9c1f7d4e54c3)'
        appType: 'functionApp'
        appName: '$(functionAppName)'
        package: '$(packagePath)'
