trigger: none

resources:
  pipelines:
  - pipeline: ci                  # alias (à réutiliser plus bas)
    source: amira2200.pfe2025     # NOM EXACT du pipeline CI (tel qu'affiché dans DevOps)
    trigger: true                 # déclenche ce CD quand la CI réussit

pool:
  name: Default

variables:
  functionAppName: 'amira-functionapp'
  artifactName: 'drop'            # doit matcher PublishBuildArtifacts de la CI
  packagePath: '$(Pipeline.Workspace)/ci/$(artifactName)/functionapp.zip'

stages:
- stage: Deploy
  displayName: 'Deploy to Azure Function App'
  jobs:
  - job: DeployJob
    steps:
    - download: ci                # même alias que ci-dessus
      artifact: $(artifactName)

    - task: AzureWebApp@1
      displayName: 'Deploy $(packagePath) to $(functionAppName)'
      inputs:
        azureSubscription: 'Azure subscription 1'
        appType: 'functionApp'    # c'est bien une Azure Function
        appName: '$(functionAppName)'
        package: '$(packagePath)'
