trigger:
- master   # mets 'main' si c'est ta branche par défaut

pool:
  name: Default   # ton agent self-hosted

variables:
  PYTHON_VERSION: '3.10'

steps:
# 1) (optionnel sur self-hosted) sélection de version Python
- task: UsePythonVersion@0
  displayName: 'Use Python $(PYTHON_VERSION)'
  inputs:
    versionSpec: '$(PYTHON_VERSION)'
    addToPath: true

# 2) Installer les dépendances dans .python_packages à la racine
- script: |
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt --target=".python_packages/lib/site-packages"
  displayName: 'Install deps → .python_packages/'

# 3) Staging minimal (on garde local.settings.json)
- task: CopyFiles@2
  displayName: 'Stage files for package'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: |
      host.json
      local.settings.json   # <<< on l'inclut
      requirements.txt
      shared.py
      **/*.py
      .python_packages/**/*
      !.git/**/*
      !.vscode/**/*
      !**/__pycache__/**/*
      !**/*.pyc
      !**/.venv/**/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)/package'

# 4) ZIP déployable
- task: ArchiveFiles@2
  displayName: 'Zip package'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/package'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/functionapp.zip'
    replaceExistingArchive: true

# 5) Publier l’artefact
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
    publishLocation: 'Container'


